#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias vault="sshfs ubuntu@segdon.com:/home/ubuntu/vault /mnt/remote/wall/ -C -p 10015"
alias isoserver="sshfs gandalf@segdon.com:/ /mnt/remote/isoserver/ -C -p 10100"
alias server="sshfs gandalf@segdon.com:/ /mnt/remote/server/ -C -p 10010"
alias mpbca="sshfs nostro@segdon.com:/ /mnt/remote/mbpca/ -C -p 10021"
alias attic="sshfs pi@segdon.com:/ /mnt/remote/attic/ -C -p 10014"

#fix obvious typo's
alias cd..='cd ..'
alias pdw="pwd"
alias udpate='sudo pacman -Syyu'
alias upate='sudo pacman -Syyu'

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#continue download
alias wget="wget -c"

# Aliases for software managment
# eopkg
alias update='sudo eopkg upgrade'
alias eup='sudo eopkg upgrade'

# yay as aur helper - updates everything

alias copyPackages="eopkg li | cut -d ' ' -f 1 | tr '\n' ' ' > ~/InstalledPackages"
alias restorePackages='sudo eopkg install $(cat InstalledPackages)'

#merge new settings
alias merge="xrdb -merge ~/.Xresources"

#ps
alias ps="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

#improve png
alias fixpng="find . -type f -name "*.png" -exec convert {} -strip {} \;"

#add new fonts
alias update-fc='sudo fc-cache -fv'

#hardware info --short
alias hw="hwinfo --short"

#mounting the folder Public for exchange between host and guest on virtualbox
alias vbm="sudo mount -t vboxsf -o rw,uid=1000,gid=1000 Public /home/$USER/Public"

#youtube-dl
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
alias yt="youtube-dl --add-metadata -i"
alias yta="yt -x -f bestaudio/best"
alias ytv-best="youtube-dl -f bestvideo+bestaudio "

#get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

#textedits
alias cfa="nvim ~/.config/shell/aliasses"

#shutdown or reboot
alias ssn="sudo shutdown now"
alias sr="sudo reboot"

#keeping homefolder clean
alias screen="screen -c ~/.config/screenrc"

# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
	  *.deb)       ar x $1      ;;
	  *.tar.xz)    tar xf $1   ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -riv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	free="free -h" \
	gitu="git add . && git commit && git push" \
	#dots="/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME" \
	df="df -h" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hFN --color=auto --group-directories-first --ignore=.." \
	ll="ls -lFav --ignore=.."   # show long listing of all except ".." \
	l="ls -lFav --ignore=.?*"   # show long listing but no hidden dotfiles except "." \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	q="exit" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
